#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipyparallel
Version  : 8.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/9d/d3/15024212544a74876d4000cddab15c10642e742ffd5515a65a7db1eb817f/ipyparallel-8.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9d/d3/15024212544a74876d4000cddab15c10642e742ffd5515a65a7db1eb817f/ipyparallel-8.0.0.tar.gz
Summary  : Interactive Parallel Computing with IPython
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ipyparallel-bin = %{version}-%{release}
Requires: ipyparallel-data = %{version}-%{release}
Requires: ipyparallel-license = %{version}-%{release}
Requires: ipyparallel-python = %{version}-%{release}
Requires: ipyparallel-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(decorator)
BuildRequires : pypi(entrypoints)
BuildRequires : pypi(ipykernel)
BuildRequires : pypi(ipython)
BuildRequires : pypi(jupyter_client)
BuildRequires : pypi(jupyter_server)
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(myst_parser)
BuildRequires : pypi(nbsphinx)
BuildRequires : pypi(notebook)
BuildRequires : pypi(numpy)
BuildRequires : pypi(packaging)
BuildRequires : pypi(psutil)
BuildRequires : pypi(pydata_sphinx_theme)
BuildRequires : pypi(python_dateutil)
BuildRequires : pypi(pyzmq)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(sphinx_copybutton)
BuildRequires : pypi(testpath)
BuildRequires : pypi(tornado)
BuildRequires : pypi(tqdm)
BuildRequires : pypi(traitlets)
BuildRequires : pypi(wheel)

%description
# Interactive Parallel Computing with IPython
IPython Parallel (`ipyparallel`) is a Python package and collection of CLI scripts for controlling clusters of IPython processes, built on the Jupyter protocol.

%package bin
Summary: bin components for the ipyparallel package.
Group: Binaries
Requires: ipyparallel-data = %{version}-%{release}
Requires: ipyparallel-license = %{version}-%{release}

%description bin
bin components for the ipyparallel package.


%package data
Summary: data components for the ipyparallel package.
Group: Data

%description data
data components for the ipyparallel package.


%package license
Summary: license components for the ipyparallel package.
Group: Default

%description license
license components for the ipyparallel package.


%package python
Summary: python components for the ipyparallel package.
Group: Default
Requires: ipyparallel-python3 = %{version}-%{release}

%description python
python components for the ipyparallel package.


%package python3
Summary: python3 components for the ipyparallel package.
Group: Default
Requires: python3-core
Provides: pypi(ipyparallel)
Requires: pypi(decorator)
Requires: pypi(entrypoints)
Requires: pypi(ipykernel)
Requires: pypi(ipython)
Requires: pypi(jupyter_client)
Requires: pypi(jupyter_server)
Requires: pypi(matplotlib)
Requires: pypi(myst_parser)
Requires: pypi(nbsphinx)
Requires: pypi(notebook)
Requires: pypi(numpy)
Requires: pypi(psutil)
Requires: pypi(pydata_sphinx_theme)
Requires: pypi(python_dateutil)
Requires: pypi(pyzmq)
Requires: pypi(sphinx)
Requires: pypi(sphinx_copybutton)
Requires: pypi(testpath)
Requires: pypi(tornado)
Requires: pypi(tqdm)
Requires: pypi(traitlets)

%description python3
python3 components for the ipyparallel package.


%prep
%setup -q -n ipyparallel-8.0.0
cd %{_builddir}/ipyparallel-8.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637352408
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipyparallel
cp %{_builddir}/ipyparallel-8.0.0/COPYING.md %{buildroot}/usr/share/package-licenses/ipyparallel/2c15eff35efcbd62ef860412b46613a6a194fbc3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_notebook_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/tree.d/ipyparallel.json

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ipcluster
/usr/bin/ipcontroller
/usr/bin/ipengine

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/labextensions/ipyparallel-labextension/build_log.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/install.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/package.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/schemas/ipyparallel-labextension/package.json.orig
/usr/share/jupyter/labextensions/ipyparallel-labextension/schemas/ipyparallel-labextension/plugin.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/lab_lib_index_js.1c1a47b1117814fc795e.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/lab_lib_index_js.1c1a47b1117814fc795e.js.map
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/remoteEntry.f859a4bc58cff8b91ec1.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/remoteEntry.f859a4bc58cff8b91ec1.js.map
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/style.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-313cda.e8f82e0a569f9c85299c.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-313cda.e8f82e0a569f9c85299c.js.map
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/vendors-node_modules_lumino_polling_dist_index_es6_js.8d1ca2ec4b48d2049f48.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/vendors-node_modules_lumino_polling_dist_index_es6_js.8d1ca2ec4b48d2049f48.js.map
/usr/share/jupyter/nbextensions/ipyparallel/clusterlist.css
/usr/share/jupyter/nbextensions/ipyparallel/clusterlist.js
/usr/share/jupyter/nbextensions/ipyparallel/main.js

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipyparallel/2c15eff35efcbd62ef860412b46613a6a194fbc3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
